### ISSUE TITLE
[3.6.0][Arduino][MAX485][MX-106R] Issue: Error compiling code with DynamixelSDK library

### ISSUE THREAD

**Issue by KSonaike** [ROBOTIS-GIT/DynamixelSDK#202] opened 2018-06-21 15:57 UTC
Hi,

I've got 2 MX106R servos that I would like to control using an Arduino Mega 2560 microcontroller. I've carefully followed the given instruction (link below) on how to setup the DynamixelSDK library to use on the Arduino software. But have had no luck when compiling the code as the map library and I suspect others are missing/not supported.

Any suggestions or corrections are greatly appreciated
Many thanks

Error screenshot link
https://ibb.co/cRyQAT

instructions given to setup DynamixelSDK library
https://github.com/ROBOTIS-GIT/DynamixelSDK/blob/master/c%2B%2B/README.md

**Comment by OpusK** [comment] 2018-06-22 06:10
Hi, @KSonaike 

I'm sorry for the inconvenience caused by the wrong information in the README.
So, I deleted README.

I'm so sorry about wrong information in README.
So, I deleted README.

DynamixelSDK is not a compatible source for embedded system. Only OS support.
Of course, some libraries have been ported for embedded system such as OpenCR, OpenCM9.04.
But, basically DynamixelSDK is not working on embedded board.

So, if you want use Dynamixel on common Arduino board, you can use [DynamixelShield](https://github.com/ROBOTIS-GIT/DynamixelShield) instead DynamixelSDK.
However, you have to configure the circuit for Dynamixel yourself.

Dynamixel Shield will be released and you can use this product also.

**Closed** 2018-06-23 02:38 UTC
Labels: in progress, question
