### ISSUE TITLE
PInvokeStackImbalance errors in Visual Studio with SDK 3.5.4

### ISSUE THREAD

**Issue by Miedlar** [ROBOTIS-GIT/DynamixelSDK#170] opened 2018-03-08 20:01 UTC
I'm not sure3 this is the proper place to put this, but if you run into this, please be aware that this is a Microsoft issue.  You can turn off this "feature" but going into the "Managed Debuggunbg Assistants" (hit ctrl-alt-E to get to it) and uncheck that value.  I hope this helps!

**Comment by ROBOTIS-Leon** [comment] 2018-03-09 00:32
@Miedlar 

Hi, 
thank you for the advice

I wondered if you were trying to do build the SDK C#, and saw PInvokeStackImbalance exception caused by CallingConvention problem.

**Comment by Miedlar** [comment] 2018-03-09 01:15
Leon,

I wasn't trying to build the SDK itself, I was just using the C dll via
Import DLL.  I was basing my code on the ping and read-write samples
included with the SDK.   But yes, I think the Calling Convention was in
play here.

I hope that helps.  If you need more info, please let me know.

BTW, according to the research I did, this was something that crept in
between Visual Studio 2008 and 2010.

M**2

**Comment by ROBOTIS-Leon** [comment] 2018-03-09 02:00
@Miedlar 

Understood. I will leave this on closed issue, since someone who wants to get their answers used to search information either from closed issue.

do you agree?

**Comment by Miedlar** [comment] 2018-03-09 11:00
Leon,

Absolutely, I only put in there at Brandon's request, I wasn't sure it was
the proper place to put it.  But I think we wanted me to share what I'd
found with y'all.  I hope it's of use to you.

M**2

**Comment by Miedlar** [comment] 2018-03-09 11:16
Leon,

If it helps, take a look at:

https://stackoverflow.com/questions/3506796/pinvokestackimbalance-how-can-i-fix-this-or-turn-it-off

That tells more about what's up and what you (and I do mean you, as in you
at Robotis) can do about it.

M**2

**Comment by ROBOTIS-Leon** [comment] 2018-03-15 08:36
@Miedlar 

Thank you for great ideas from you
It seems like the SDK DLL C ver, C# porting should be modified in next release

**Comment by Miedlar** [comment] 2018-03-15 10:01
Leon,

I'm glad it helped.

M**2

**Comment by ROBOTIS-Leon** [comment] 2018-05-15 05:03
@Miedlar 

Hi, again,

since the visual studio 2008 is no longer available via official download center in microsoft page, 
we are thinking no many related issues will be made afterwards. 
but anyway the users who will see invoke problem, will see this issue, though this is closed.

Thank you for the advice, again, and let me close this issue.

**Closed by ROBOTIS-Leon** 2018-05-15 05:03 UTC
Labels: enhancement, in progress

**Comment by Miedlar** [comment] 2018-05-15 09:59
Leon,

I am uncertain what Vis Studio 2008 has to do with this, I use 2015 myself
and the issue stil exists in there.

M**2
